#!/bin/sh

echo "Install git hooks..."
touch .git/hooks/pre-commit
echo "#!/bin/sh

./run composer run test" > .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
echo " done!\n"

echo "Build image..."
image_name="php-xray"
dockerfile="Dockerfile.xray"

docker build \
  --tag "${image_name}" \
  --file "${dockerfile}" \
  --build-arg UID="$(id -u)" \
  "."

echo " done!\n"
