name: CI
on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Checkout & Build & Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile.xray
          push: false
          tags: php-xray
      - name: Test
        uses: addnab/docker-run-action@v3
        with:
          image: php-xray
          options: --user root --volume ${{ github.workspace }}:${{ github.workspace }} --workdir ${{ github.workspace }}
          run: |
            composer test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          verbose: true
          fail_ci_if_error: true
